Back end file structure
FACG6/AMiDEAST pull request #51
Opened 2019-04-17 06:26 UTC by Fatmasiam

#2

2019-04-17 06:34 UTC, AbdallahAmmar96 approved these changes

2019-04-17 12:34 UTC, naremanhilles approved these changes

2019-04-17 13:55 UTC, kannanhassouna requested changes
1 - change ``` server/database/quires ``` to ``` server/database/queries ```
2 - change ``` server/middlewares/authontication ``` to ``` server/middlewares/authentication ```

2019-04-18 06:14 UTC, kannanhassouna approved these changes

2019-04-18 07:19 UTC, naremanhilles approved these changes

2019-04-18 07:21 UTC, merged