Footer component
FACG6/AMiDEAST pull request #58
Opened 2019-04-17 10:54 UTC by naremanhilles

2019-04-17 11:06 UTC, Fatmasiam approved these changes

2019-04-17 17:00 UTC, kannanhassouna requested changes
Where the style of component

2019-04-17 17:00 UTC, knanahassouna1 commented on Client/src/components/common/footer.jsx
> +import React, { Component } from 'react';
remove unnecessary classes 
```suggestion
import React from 'react';
```

2019-04-17 17:00 UTC, knanahassouna1 commented on Client/src/components/common/footer.jsx
> +     <i class="fab fa-facebook-f"></i>
Indentation !!!

2019-04-18 07:33 UTC, naremanhilles commented
> Where the style of component

2019-04-18 07:33 UTC, closed without merging

2019-04-18 07:35 UTC, naremanhilles commented
style is abdullah's task.