label component
FACG6/AMiDEAST pull request #59
Opened 2019-04-17 11:14 UTC by naremanhilles

Relates #13

2019-04-17 11:50 UTC, AbdallahAmmar96 commented
add a new line at the end of the file

2019-04-17 17:02 UTC, kannanhassouna requested changes
the style of component

2019-04-17 17:04 UTC, kannanhassouna requested changes

2019-04-17 17:04 UTC, knanahassouna1 commented on Client/src/components/common/label.jsx
> +return(
Indentation

2019-04-18 11:15 UTC, naremanhilles commented on Client/src/components/common/label.jsx
> +return(
> Indentation

edit it :+1:

2019-04-18 13:29 UTC, AbdallahAmmar96 requested changes

2019-04-18 13:29 UTC, AbdallahAmmar96 commented on Client/src/components/common/label.jsx
> +    {props.labelText}
you can do destruture object 
const { id, labelText } = props
befor the return line

2019-04-18 13:29 UTC, AbdallahAmmar96 commented on Client/src/components/common/Label/index.js
> +  return (
add new line after 2

2019-04-18 13:29 UTC, AbdallahAmmar96 commented on Client/src/components/common/date-picker/index.js
> +  return (
add a new line after 1

2019-04-18 13:29 UTC, AbdallahAmmar96 commented on Client/src/components/common/date-picker/index.js
> +  return (
change Datepicker to DatePicker

2019-04-18 13:29 UTC, AbdallahAmmar96 commented on Client/src/components/common/date-picker/index.js
> +export default Datepicker;
change Datepicker to DatePicker

2019-04-18 13:29 UTC, AbdallahAmmar96 commented on Client/src/components/common/date-picker/index.js
> +  );
make this option a component so we can reuse it

2019-04-18 13:29 UTC, AbdallahAmmar96 commented on Client/src/components/common/Label/index.js
> +}
you can make a destruction 
const { id, labelText } = props

2019-04-22 08:38 UTC, closed without merging