link component
FACG6/AMiDEAST pull request #61
Opened 2019-04-17 11:56 UTC by naremanhilles

Relates #24

2019-04-17 13:53 UTC, AbdallahAmmar96 approved these changes

2019-04-17 17:05 UTC, kannanhassouna requested changes
the Style Again

2019-04-17 17:05 UTC, knanahassouna1 commented on Client/src/components/common/Link/index.js
> +function Link(props){
Indentation

2019-04-18 11:06 UTC, naremanhilles commented
style fatma task.

2019-04-18 18:22 UTC, Fatmasiam commented
There is conflict ?! solve it

2019-04-21 08:59 UTC, knanahassouna1 commented
@naremanhilles Solve the conflict

2019-04-22 13:42 UTC, closed without merging