Add button
FACG6/AMiDEAST pull request #67
Opened 2019-04-18 09:04 UTC by mohammedmh

add button with style and some App basic style

2019-04-18 11:13 UTC, Fatmasiam requested changes
Remove any File that not related to the pull request

2019-04-18 11:13 UTC, Fatmasiam commented on Client/src/components/Button/Button.js
> +      'Fn' : () => { console.log('moammed')} ,
Convert it to stateless component !!

2019-04-18 11:13 UTC, Fatmasiam commented on Client/src/components/Button/Button.css
> +    background-color: #06468F;
make className more specific !!

2019-04-18 11:15 UTC, Fatmasiam reviewed
Conflict in App.js file !!!

2019-04-18 16:34 UTC, knanahassouna1 commented
change the branch name and solve the conflict

2019-04-21 07:20 UTC, kannanhassouna requested changes
test your component before push it.
remove  all un-related files. 
remove your syntax.

2019-04-21 07:20 UTC, knanahassouna1 commented on Client/src/components/App.js
> +import Button from './Button/Button';
Remove useless modules

2019-04-21 07:20 UTC, knanahassouna1 commented on Client/src/components/App.css
> +* {
i think you should remove the pull request. 
because that is added in ``` index.css ```

2019-04-21 07:20 UTC, knanahassouna1 commented on package.json
> +    "concurrently": "^4.1.0",
remove all un-related modules

2019-04-21 07:20 UTC, knanahassouna1 commented on test/testQueires.js
> +let test = require('tape');
remove the test. your pull request for the button not for testing

2019-04-21 07:20 UTC, knanahassouna1 commented on test/testRoutes.js
> +let test = require('tape');
also here

2019-04-21 07:20 UTC, knanahassouna1 commented on server/package.json
> +    "eslint-plugin-import": "^2.17.1"
remove un-related files

2019-04-21 07:20 UTC, knanahassouna1 commented on Client/src/components/Button/Button.js
> +            <button className={this.props.btn-classname } onClick ={this.props.handlevent }>{this.props.btn-value}</button>
syntax error. 
review the whole file you have a problem with syntax.

2019-04-21 07:20 UTC, knanahassouna1 commented
Solve the conflict. 
add all your teammates in review

2019-04-23 07:12 UTC, closed without merging