19 sidebar component
FACG6/AMiDEAST pull request #73
Opened 2019-04-20 11:28 UTC by Fatmasiam

#19

2019-04-20 12:00 UTC, kannanhassouna requested changes

2019-04-20 12:00 UTC, knanahassouna1 commented on Client/src/components/common/Link/index.css
> +.sublink{
again class name, always be more specific. 
```
sidebar-sublink
```

2019-04-20 12:00 UTC, knanahassouna1 commented on Client/src/components/common/Link/index.css
> +  font-size: 16px;
font-size by default 16px

2019-04-20 12:00 UTC, knanahassouna1 commented on Client/src/components/common/Sidebar/index.js
> +      <hr className='hr' />
again generic class name

2019-04-20 12:00 UTC, knanahassouna1 commented on Client/src/components/common/Sidebar/index.js
> +        {linklist.map((linklist, index) => <Linklst key={index} links={linklist} />)}
```suggestion
        {linklist.map((linklist, index) => <Linklist key={index} links={linklist} />)}
```

2019-04-20 12:00 UTC, knanahassouna1 commented on Client/src/components/common/Sidebar/index.css
> +  width: 20%;
good idea

2019-04-20 12:00 UTC, knanahassouna1 commented on Client/src/components/common/Sidebar/index.js
> +import Linklst from '../LinkList';
```suggestion
import Linklist from '../LinkList';
```

2019-04-20 12:00 UTC, knanahassouna1 commented on Client/src/components/common/LinkList/index.css
> +}
new line

2019-04-20 12:00 UTC, knanahassouna1 commented on Client/src/components/common/Link/index.js
> +    <li className='sublink'> {link.title} </li>
```suggestion
<Link  to={link.to}> 
      <li className='sublink'> {link.title} </li>
</Link>
  ```

2019-04-20 12:00 UTC, knanahassouna1 commented on Client/src/components/common/LinkList/index.js
> +      <i className={links.fontawesomeClass} ></i>
```suggestion
      <i className={links.fontAwesome} ></i>
```

2019-04-20 12:25 UTC, Fatmasiam commented on Client/src/components/common/Link/index.css
> +  font-size: 16px;
@knanahassouna1  the default is ```18px```

2019-04-20 12:28 UTC, Fatmasiam commented on Client/src/components/common/Sidebar/index.js
> +      <hr className='hr' />
@knanahassouna1  do you mean to hr?

2019-04-21 08:55 UTC, kannanhassouna approved these changes

2019-04-21 08:55 UTC, kannanhassouna commented on Client/src/components/common/Link/index.css
> +  font-size: 16px;
https://www.google.com/search?q=default+font+size+of+html&oq=default+font-size+&aqs=chrome.1.69i57j0l5.5205j0j1&sourceid=chrome&ie=UTF-8

2019-04-21 08:55 UTC, kannanhassouna commented on Client/src/components/common/LinkList/index.js
> +export default function Linklist({ links }) {
```suggestion
export default function Linklist({ links: { links}  }) {
```

2019-04-21 08:55 UTC, kannanhassouna commented on Client/src/components/common/LinkList/index.js
> +          console.log(link.title, link.to)
remove console.log

2019-04-21 08:55 UTC, kannanhassouna commented on Client/src/components/common/LinkList/index.js
> +        {links.links.map((link, index) => {
```suggestion
        {links.links.map(({ title, to }, index) => {
```

2019-04-22 08:27 UTC, AbdallahAmmar96 commented on Client/src/components/common/Link/index.js
> +  return (to ?
remove the console.log(title)
line 6

2019-04-22 08:31 UTC, AbdallahAmmar96 commented on Client/src/components/common/Link/index.js
> +
### For the import arrangement
- first: import third-party modules
- second: import your files 
and between them add a new line

2019-04-22 08:32 UTC, AbdallahAmmar96 commented on Client/src/components/common/Link/index.js
> +
```suggestion
import React from 'react';
import { Link } from 'react-router-dom';

import './index.css';
```

2019-04-22 08:32 UTC, AbdallahAmmar96 commented on Client/src/components/common/Link/index.js
> +
see code below

2019-04-22 08:47 UTC, AbdallahAmmar96 commented on Client/src/components/common/LinkList/index.js
> +        }
```suggestion
        return <Link key={index} title={link.title} to={link.to} />
        }
```
indentation

2019-04-22 09:10 UTC, AbdallahAmmar96 commented on Client/src/components/common/Sidebar/index.js
> +
same comment above for the arrangement

2019-04-22 09:33 UTC, AbdallahAmmar96 commented on Client/src/components/common/Sidebar/index.js
> +      title: 'Home',
Put the defaultProps in an external static file and call it here

2019-04-22 13:59 UTC, AbdallahAmmar96 approved these changes

2019-04-22 13:59 UTC, merged