35 add course
FACG6/AMiDEAST pull request #84
Opened 2019-04-22 21:46 UTC by naremanhilles

2019-04-23 08:27 UTC, knanahassouna1 commented
Description ?!!

2019-04-23 09:28 UTC, AsalaKM commented
@naremanhilles  Please!
- Write a clear description for your work
- It can't be in progress and need review in the same time

2019-04-23 17:18 UTC, knanahassouna1 commented
@naremanhilles , Good job btw. 
but you have a lot of repeated code you should take care of that

2019-04-24 11:19 UTC, AbdallahAmmar96 requested changes

2019-04-24 11:19 UTC, AbdallahAmmar96 commented on Client/src/components/Layout/Desktop/index.css
> +}
Don't use the body tag in css 
add a class and use it

2019-04-24 11:19 UTC, AbdallahAmmar96 commented on Client/src/components/Layout/Desktop/index.js
> +import React, { Component } from "react";
use single quotation 
```suggestion
import React, { Component } from 'react';
```

2019-04-24 11:19 UTC, AbdallahAmmar96 commented on Client/src/components/Layout/Desktop/index.js
>  import { BrowserRouter, Route, Switch, Redirect } from "react-router-dom";
use single quotation
```suggestion
import { BrowserRouter, Route, Switch, Redirect } from 'react-router-dom';
```

2019-04-24 11:19 UTC, AbdallahAmmar96 commented on Client/src/components/Layout/Desktop/index.js
> -import Footer from '../DesktopFooter';
add a new line after import third module

2019-04-24 11:19 UTC, AbdallahAmmar96 commented on Client/src/components/Layout/Desktop/index.js
> +            <Sidebar />
className s ?? 
use readable names

2019-04-24 11:19 UTC, AbdallahAmmar96 commented on Client/src/components/Layout/Desktop/index.js
>              </Switch>
use single quotation

2019-04-24 14:02 UTC, AsalaKM requested changes

2019-04-24 14:02 UTC, AsalaKM commented on Client/src/components/Layout/Desktop/index.js
> +import React, { Component } from "react";
@naremanhilles  check your eslint

2019-04-24 14:02 UTC, AsalaKM commented on Client/src/components/contanier/staff/Courses/AddCourse/index.css
> +  margin-bottom: 9px;
In all your work
```
margin-top: 50px;
  margin-left: 39px;
  margin-bottom: 9px;
```
replace it with 
```
margin:;
```
use one property to reduce your lines

2019-04-24 14:02 UTC, AsalaKM commented on Client/src/components/contanier/staff/Courses/AddCourse/index.css
> +.start-input {
`.start-input` and `.end-input`
`..start-label ` and `.end-label `
the same style for both !!
use one class for it 
don't repeat your code :+1:

2019-04-24 14:02 UTC, AsalaKM commented on Client/src/components/contanier/staff/Courses/AddCourse/index.css
> +.add-button {
remove it

2019-04-24 22:05 UTC, closed without merging