Travis
FACG6/AMiDEAST pull request #96
Opened 2019-04-23 14:07 UTC by AbdallahAmmar96

Install travis

2019-04-23 17:02 UTC, knanahassouna1 commented
you should care about the database.

2019-04-23 20:25 UTC, AsalaKM commented
Its good in this sprint
but it will changed in the next sprints

2019-04-23 20:26 UTC, AsalaKM reviewed
Its good in this sprint
but it will changed in the next sprints

2019-04-23 23:55 UTC, AbdallahAmmar96 commented
Explain !!!!
@knanahassouna1

2019-04-24 08:37 UTC, naremanhilles approved these changes

2019-04-24 08:46 UTC, kannanhassouna requested changes

2019-04-24 08:46 UTC, knanahassouna1 commented on .travis.yml
> +  - PGPORT=5433
```suggestion
  - PGPORT=5432
```

2019-04-24 09:27 UTC, kannanhassouna approved these changes

2019-04-24 09:27 UTC, Fatmasiam approved these changes

2019-04-24 09:42 UTC, merged